<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PsdTachieNext.Core/PsdTachieNext.Core.csproj" />
    <PackageReference Include="Vortice.Direct2D1" Version="[3.8.3]" />
  </ItemGroup>
</Project>
