<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType></PropertyGroup><ItemGroup>
<ProjectReference Include="../../src/PsdTachieNext.Compiler/PsdTachieNext.Compiler.csproj" />
<Compile Include="../PsdTachieNext.Tests/PsdFixture.cs" Link="PsdFixture.cs" />
</ItemGroup></Project>
